### ISSUE TITLE
problem.jsxでのミス？と思われるところを見つけましたので報告しておきます。

### ISSUE THREAD

**Issue by ferretdayo** [lepus-ctf/lepus-frontend#1]
136行目のreturn文のところです。
Can't find a problem.
のCan'tのシングルクォートの終わりが無く、136行目以降にも影響が出ている感じがします。
Can\'t find a problem.
にしてエスケープすればよいかと思います。よろしくお願いします。

**Comment by mzyy94** [comment]
ご報告どうもありがとうございます。
ReactJSXの記法としては、シングルクオートはエスケープしないで書くようになっているのですが、
JSXのソースコードシンタックスハイライトが整備されていないため、エディタやGitHubなどではJSXシングルクオートを文字列の開始記号として処理してしまい、コードが見づらくなる現象が発生しています。
シンタックスエラーと捉えられる可能性もあることは感じており、なにかよい解決方法がないか模索したのですが、
`\'`とするとそのままDOMに書きだされて、_Can\'t find a problem._と表示されてしまうので、
このIssueに関してはwontfixとさせていただきます。

**Comment by mzyy94** [comment]
wontfixとしていましたが、可読性優先で、`Can't`から`Cannot`に変更しました。
ご報告有り難うございました。 :+1: 

6a3da928950baf86a4259e6982226cdb3a1890a3
